

import numpy as np
import os

def generate_demo_nc():
    try:
        import netCDF4 as nc
    except ImportError:
        print("netCDF4 not installed, trying scipy...")
        _generate_with_scipy()
        return

    os.makedirs("data", exist_ok=True)
    path = "data/climate_demo.nc"

    lats  = np.arange(-90,  91,  2.5, dtype=np.float32)   # 73
    lons  = np.arange(-180, 180, 2.5, dtype=np.float32)   # 144
    
    years  = np.arange(1990, 2024)
    months = np.arange(1, 13)
    n_time = len(years) * len(months)               # 408

    print(f"Generating {n_time} time steps × {len(lats)} lats × {len(lons)} lons …")

    rng = np.random.default_rng(42)

  
    lat_profile = 300 - 0.5 * np.abs(lats)          # (73,)
    lon_grid    = np.ones((len(lats), len(lons)))    # (73, 144)

    temp = np.empty((n_time, len(lats), len(lons)), dtype=np.float32)
    t = 0
    for yr in years:
        for mo in months:
            seasonal  = 10 * np.cos(2*np.pi*(mo-1)/12) * (lats/90)   # (73,)
            warming   = 0.025 * (yr - 1990)                            # scalar
            noise     = rng.normal(0, 1.5, (len(lats), len(lons)))    # (73,144)
            land_bump = 3 * np.sin(np.deg2rad(lons))[np.newaxis, :]   # (1,144)
            temp[t]   = (lat_profile[:, np.newaxis] + lon_grid * seasonal[:, np.newaxis]
                         + warming + noise + land_bump)
            t += 1

    
    precip = np.empty((n_time, len(lats), len(lons)), dtype=np.float32)
    t = 0
    for yr in years:
        for mo in months:
            itcz   = 8 * np.exp(-((lats - 5)**2) / 200)[:, np.newaxis]
            midlat = 3 * np.exp(-((np.abs(lats) - 50)**2) / 100)[:, np.newaxis]
            pole   = 1.5 * np.exp(-((np.abs(lats) - 70)**2) / 80)[:, np.newaxis]
            season = 1 + 0.4 * np.sin(2*np.pi*(mo-1)/12)
            noise  = rng.exponential(0.5, (len(lats), len(lons)))
            precip[t] = np.clip((itcz + midlat + pole) * season + noise, 0, None)
            t += 1

   
    wind = np.empty((n_time, len(lats), len(lons)), dtype=np.float32)
    t = 0
    for yr in years:
        for mo in months:
            jet    = 12 * np.exp(-((np.abs(lats) - 45)**2) / 150)[:, np.newaxis]
            season = 1 + 0.3 * np.cos(2*np.pi*(mo-1)/12)
            noise  = np.abs(rng.normal(0, 2, (len(lats), len(lons))))
            wind[t] = np.clip(jet * season + noise, 0, None)
            t += 1

    
    time_vals = []
    for yr in years:
        for mo in months:
            days = (yr - 1990) * 365 + (mo - 1) * 30
            time_vals.append(days)
    time_vals = np.array(time_vals, dtype=np.float64)

    
    ds = nc.Dataset(path, "w", format="NETCDF4")
    ds.title       = "PyClimaExplorer Demo Dataset (ERA5-style)"
    ds.institution = "Synthetic – generated by generate_data.py"
    ds.source      = "Synthetic ERA5-style monthly climate data 1990-2023"

    ds.createDimension("time",      n_time)
    ds.createDimension("latitude",  len(lats))
    ds.createDimension("longitude", len(lons))

    vtime = ds.createVariable("time",      "f8", ("time",))
    vlat  = ds.createVariable("latitude",  "f4", ("latitude",))
    vlon  = ds.createVariable("longitude", "f4", ("longitude",))
    vt2m  = ds.createVariable("t2m",       "f4", ("time","latitude","longitude",), zlib=True)
    vtp   = ds.createVariable("tp",        "f4", ("time","latitude","longitude",), zlib=True)
    vu10  = ds.createVariable("u10",       "f4", ("time","latitude","longitude",), zlib=True)

    vtime.units      = "days since 1990-01-01"
    vtime.calendar   = "standard"
    vlat.units       = "degrees_north"
    vlon.units       = "degrees_east"
    vt2m.units       = "K";    vt2m.long_name  = "2m Temperature"
    vtp.units        = "mm/d"; vtp.long_name   = "Total Precipitation"
    vu10.units       = "m/s";  vu10.long_name  = "10m Wind Speed"

    vtime[:]      = time_vals
    vlat[:]       = lats
    vlon[:]       = lons
    vt2m[:,:,:]   = temp
    vtp[:,:,:]    = precip
    vu10[:,:,:]   = wind

    ds.close()
    print(f"✓ Saved {path}  ({os.path.getsize(path)/1e6:.1f} MB)")


def _generate_with_scipy():
    
    from scipy.io import netcdf_file
    import os
    os.makedirs("data", exist_ok=True)
    path = "data/climate_demo.nc"
    # Reduced resolution for scipy
    lats  = np.arange(-90, 91, 5, dtype=np.float32)
    lons  = np.arange(-180, 180, 5, dtype=np.float32)
    years  = np.arange(1990, 2024)
    months = np.arange(1, 13)
    n_time = len(years) * len(months)
    rng = np.random.default_rng(42)
    lat_profile = 300 - 0.5 * np.abs(lats)
    temp = np.empty((n_time, len(lats), len(lons)), dtype=np.float32)
    t = 0
    for yr in years:
        for mo in months:
            seasonal = 10 * np.cos(2*np.pi*(mo-1)/12) * (lats/90)
            warming  = 0.025 * (yr - 1990)
            noise    = rng.normal(0, 1.5, (len(lats), len(lons)))
            temp[t]  = lat_profile[:, np.newaxis] + seasonal[:, np.newaxis] + warming + noise
            t += 1
    time_vals = np.array([(yr-1990)*365+(mo-1)*30 for yr in years for mo in months], dtype=np.float32)
    with netcdf_file(path, "w") as f:
        f.createDimension("time",      n_time)
        f.createDimension("latitude",  len(lats))
        f.createDimension("longitude", len(lons))
        vtime = f.createVariable("time",      "f", ("time",));      vtime[:] = time_vals
        vlat  = f.createVariable("latitude",  "f", ("latitude",));  vlat[:]  = lats
        vlon  = f.createVariable("longitude", "f", ("longitude",)); vlon[:]  = lons
        vt2m  = f.createVariable("t2m",       "f", ("time","latitude","longitude"))
        vt2m[:] = temp
        vt2m.units = "K"; vt2m.long_name = "2m Temperature"
    print(f"✓ Saved {path}  (scipy fallback, reduced resolution)")


if __name__ == "__main__":
    generate_demo_nc()
